### ISSUE TITLE
Contributing to Indic Acceleration 

### ISSUE THREAD

**Issue by bhuvanbharath** [protosphinx/in#3]
hey sphinx,

count me in for Indic Acceleration. can leverage my mechanical and programming skills to build stuff that can make India a better place.

unable to dm, create a pr, hence creating an issue 🙂

**Comment by protosphinx** [comment]
Can please check again? There are PRs raised such as https://github.com/protosphinx/in/pulls?q=is:pr+is:closed+
Let's sync again if that does not help
