### ISSUE TITLE
in/acc manifesto revision proposals - add as new file

### ISSUE THREAD

**Issue by lahnil** [protosphinx/in#5]
Catch-all Issue to tag any PRs related to edits in the manifesto.

Proposed file structure for the interim:
- The IndicAcceleration Manifesto.md (The original commit)
- in-acc manifesto v2 draft.md (Use this as your file name, we will figure out better organisation with upcoming issues)

**Comment by protosphinx** [comment]
well, we can merger and pull requests already https://github.com/protosphinx/in/pull/8#pullrequestreview-1615273253. So will close this "issue", it does not seem to be so.
