### ISSUE TITLE
in/acc OS: how to organize, collaborate, and deliver

### ISSUE THREAD

**Issue by lahnil** [protosphinx/in#6]
Create OS.md to document interim SOPs

Things to add:
- How to 'Issue' and 'PR'
- How to contribute
- Organisational Structure Proposals

**Comment by protosphinx** [comment]
Thanks for the bullets


- How to issue : here
- How to PR : like https://github.com/protosphinx/in/pull/8#pullrequestreview-1615273253

- How to contribute : via merge requests and more
   suggestions and brainstorming - on your preferred channel, X or Discord!

Hope that helps
